---
name: ty Type Checking

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:
    inputs:
      version:
        description: Manual Type Checking
        default: type_checking
        required: false

jobs:
  ty:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v6

      - name: Install package
        run: uv pip install . --system

      - name: Check package
        run: uvx ty check neatnet/
